// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://eyovhxussnbugokekzej.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5b3ZoeHVzc25idWdva2VremVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEyODc0MzEsImV4cCI6MjA0Njg2MzQzMX0.W1SZxUXY4_cJwPj8e2k9k_ITOJ5vI3nKRz-TT32J0O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);